title: "Open Source Endowment"
author: "Open Source Endowment Foundation"
url: "https://endowment.dev"

# SEO & Analytics 
google_tag_manager: G-XE63Z4PW8X
include: ["posthog.js", "https://www.googletagmanager.com/gtag/js?id=G-XE63Z4PW8X", "gtag.js"]
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-analytics

jekyll_analytics:
  GoogleAnalytics:          
    id: G-XE63Z4PW8X

# Social
twitter:
  username: "osendowment"
social:
  name: "Open Source Endowment"
  links:
    - "https://www.linkedin.com/company/osendowment"
    - "https://x.com/osendowment"
    - "https://fb.com/osendowment"
    - "https://github.com/osendowment"
favicon:
  standard: /img/favicon.ico
  apple_touch: /img/apple-touch-icon.png
  android_icon: /img/icon-192.png




