title: "Open Source Endowment"
author: "Open Source Endowment Foundation"
include: ["posthog.js"]
url: "https://endowment.dev"
twitter:
  username: "osendowment"
social:
  name: "Open Source Endowment"
  links:
    - "https://www.linkedin.com/company/osendowment"
    - "https://x.com/osendowment"
    - "https://fb.com/osendowment"
    - "https://github.com/osendowment"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-analytics
favicon:
  standard: /img/favicon.ico
  apple_touch: /img/apple-touch-icon.png
  android_icon: /img/icon-192.png
